// Auto-generated from MeshCore CommonCLI.cpp
// Generated: 2025-12-27
// Source: https://raw.githubusercontent.com/meshcore-dev/MeshCore/main/src/helpers/CommonCLI.cpp

export interface MeshCoreCommand {
  name: string;
  category: string;
  params: { name: string; type: string }[];
  description: string;
  serialOnly: boolean;
  hasParam: boolean;
}

export const MESHCORE_COMMANDS: MeshCoreCommand[] = [
  {
    name: "get adc.multiplier",
    category: "get",
    params: [],
    description: "Get ADC multiplier for battery",
    serialOnly: false,
    hasParam: false,
  },
  {
    name: "get advert.interval",
    category: "get",
    params: [],
    description: "Get local advert interval (minutes)",
    serialOnly: false,
    hasParam: false,
  },
  {
    name: "get af",
    category: "get",
    params: [],
    description: "Get airtime factor",
    serialOnly: false,
    hasParam: false,
  },
  {
    name: "get agc.reset.interval",
    category: "get",
    params: [],
    description: "Get AGC reset interval (seconds)",
    serialOnly: false,
    hasParam: false,
  },
  {
    name: "get allow.read.only",
    category: "get",
    params: [],
    description: "Get read-only access setting",
    serialOnly: false,
    hasParam: false,
  },
  {
    name: "get bridge.baud",
    category: "get",
    params: [],
    description: "Get bridge baud rate",
    serialOnly: false,
    hasParam: false,
  },
  {
    name: "get bridge.channel",
    category: "get",
    params: [],
    description: "Get bridge channel (ESP-NOW)",
    serialOnly: false,
    hasParam: false,
  },
  {
    name: "get bridge.delay",
    category: "get",
    params: [],
    description: "Get bridge delay (ms)",
    serialOnly: false,
    hasParam: false,
  },
  {
    name: "get bridge.enabled",
    category: "get",
    params: [],
    description: "Get bridge enabled status",
    serialOnly: false,
    hasParam: false,
  },
  {
    name: "get bridge.secret",
    category: "get",
    params: [],
    description: "Get bridge encryption secret",
    serialOnly: false,
    hasParam: false,
  },
  {
    name: "get bridge.source",
    category: "get",
    params: [],
    description: "Get bridge packet source",
    serialOnly: false,
    hasParam: false,
  },
  {
    name: "get bridge.type",
    category: "get",
    params: [],
    description: "Get bridge type (rs232/espnow/none)",
    serialOnly: false,
    hasParam: false,
  },
  {
    name: "get direct.txdelay",
    category: "get",
    params: [],
    description: "Get direct TX delay factor",
    serialOnly: false,
    hasParam: false,
  },
  {
    name: "get flood.advert.interval",
    category: "get",
    params: [],
    description: "Get flood advert interval (hours)",
    serialOnly: false,
    hasParam: false,
  },
  {
    name: "get flood.max",
    category: "get",
    params: [],
    description: "Get max flood hops",
    serialOnly: false,
    hasParam: false,
  },
  {
    name: "get freq",
    category: "get",
    params: [],
    description: "Get frequency (MHz)",
    serialOnly: false,
    hasParam: false,
  },
  {
    name: "get guest.password",
    category: "get",
    params: [],
    description: "Get guest password",
    serialOnly: false,
    hasParam: false,
  },
  {
    name: "get int.thresh",
    category: "get",
    params: [],
    description: "Get interference threshold",
    serialOnly: false,
    hasParam: false,
  },
  {
    name: "get lat",
    category: "get",
    params: [],
    description: "Get latitude",
    serialOnly: false,
    hasParam: false,
  },
  {
    name: "get lon",
    category: "get",
    params: [],
    description: "Get longitude",
    serialOnly: false,
    hasParam: false,
  },
  {
    name: "get multi.acks",
    category: "get",
    params: [],
    description: "Get multi-ack setting",
    serialOnly: false,
    hasParam: false,
  },
  {
    name: "get name",
    category: "get",
    params: [],
    description: "Get node name",
    serialOnly: false,
    hasParam: false,
  },
  {
    name: "get prv.key",
    category: "get",
    params: [],
    description: "Get private key (serial only)",
    serialOnly: true,
    hasParam: false,
  },
  {
    name: "get public.key",
    category: "get",
    params: [],
    description: "Get public key (hex)",
    serialOnly: false,
    hasParam: false,
  },
  {
    name: "get radio",
    category: "get",
    params: [],
    description: "Get radio params (freq,bw,sf,cr)",
    serialOnly: false,
    hasParam: false,
  },
  {
    name: "get repeat",
    category: "get",
    params: [],
    description: "Get repeat/forward status (on/off)",
    serialOnly: false,
    hasParam: false,
  },
  {
    name: "get role",
    category: "get",
    params: [],
    description: "Get device role",
    serialOnly: false,
    hasParam: false,
  },
  {
    name: "get rxdelay",
    category: "get",
    params: [],
    description: "Get RX delay base",
    serialOnly: false,
    hasParam: false,
  },
  {
    name: "get tx",
    category: "get",
    params: [],
    description: "Get TX power (dBm)",
    serialOnly: false,
    hasParam: false,
  },
  {
    name: "get txdelay",
    category: "get",
    params: [],
    description: "Get TX delay factor",
    serialOnly: false,
    hasParam: false,
  },
  {
    name: "gps",
    category: "gps",
    params: [],
    description: "Show GPS status",
    serialOnly: false,
    hasParam: false,
  },
  {
    name: "gps advert",
    category: "gps",
    params: [],
    description: "Get/set GPS advert location policy",
    serialOnly: false,
    hasParam: true,
  },
  {
    name: "gps off",
    category: "gps",
    params: [],
    description: "Disable GPS",
    serialOnly: false,
    hasParam: true,
  },
  {
    name: "gps on",
    category: "gps",
    params: [],
    description: "Enable GPS",
    serialOnly: false,
    hasParam: true,
  },
  {
    name: "gps setloc",
    category: "gps",
    params: [],
    description: "Set node location from GPS",
    serialOnly: false,
    hasParam: true,
  },
  {
    name: "gps sync",
    category: "gps",
    params: [],
    description: "Sync time from GPS",
    serialOnly: false,
    hasParam: true,
  },
  {
    name: "log",
    category: "logging",
    params: [],
    description: "Dump log file (serial only)",
    serialOnly: true,
    hasParam: false,
  },
  {
    name: "log erase",
    category: "logging",
    params: [],
    description: "Erase log file",
    serialOnly: false,
    hasParam: true,
  },
  {
    name: "log start",
    category: "logging",
    params: [],
    description: "Start packet logging",
    serialOnly: false,
    hasParam: true,
  },
  {
    name: "log stop",
    category: "logging",
    params: [],
    description: "Stop packet logging",
    serialOnly: false,
    hasParam: true,
  },
  {
    name: "neighbor.remove",
    category: "neighbor",
    params: [],
    description: "Remove neighbor by pubkey",
    serialOnly: false,
    hasParam: true,
  },
  {
    name: "neighbors",
    category: "neighbor",
    params: [],
    description: "List neighbors",
    serialOnly: false,
    hasParam: false,
  },
  {
    name: "get",
    category: "other",
    params: [],
    description: "Execute get command",
    serialOnly: false,
    hasParam: true,
  },
  {
    name: "set",
    category: "other",
    params: [{"name": "value", "type": "float"}, {"name": "value", "type": "int"}, {"name": "value", "type": "int"}],
    description: "Execute set command",
    serialOnly: false,
    hasParam: true,
  },
  {
    name: "tempradio",
    category: "radio",
    params: [{"name": "value", "type": "int"}, {"name": "value", "type": "int"}, {"name": "value", "type": "int"}],
    description: "Apply temporary radio params (freq bw sf cr timeout_mins)",
    serialOnly: false,
    hasParam: true,
  },
  {
    name: "sensor get",
    category: "sensor",
    params: [],
    description: "Get sensor/custom variable value",
    serialOnly: false,
    hasParam: true,
  },
  {
    name: "sensor list",
    category: "sensor",
    params: [{"name": "value", "type": "int"}],
    description: "List all sensor/custom variables",
    serialOnly: false,
    hasParam: true,
  },
  {
    name: "sensor set",
    category: "sensor",
    params: [],
    description: "Set sensor/custom variable value",
    serialOnly: false,
    hasParam: true,
  },
  {
    name: "set adc.multiplier",
    category: "set",
    params: [{"name": "value", "type": "float"}],
    description: "Set ADC multiplier",
    serialOnly: false,
    hasParam: true,
  },
  {
    name: "set advert.interval",
    category: "set",
    params: [{"name": "value", "type": "int"}, {"name": "value", "type": "string"}],
    description: "Set local advert interval (60-240 min, 0=off)",
    serialOnly: false,
    hasParam: true,
  },
  {
    name: "set af",
    category: "set",
    params: [{"name": "value", "type": "float"}, {"name": "value", "type": "int"}, {"name": "value", "type": "int"}, {"name": "value", "type": "int"}],
    description: "Set airtime factor (0-9)",
    serialOnly: false,
    hasParam: true,
  },
  {
    name: "set agc.reset.interval",
    category: "set",
    params: [{"name": "value", "type": "int"}, {"name": "value", "type": "int"}, {"name": "value", "type": "int"}],
    description: "Set AGC reset interval (seconds, rounded to 4)",
    serialOnly: false,
    hasParam: true,
  },
  {
    name: "set allow.read.only",
    category: "set",
    params: [{"name": "value", "type": "int"}],
    description: "Set read-only access (on/off)",
    serialOnly: false,
    hasParam: true,
  },
  {
    name: "set bridge.baud",
    category: "set",
    params: [{"name": "value", "type": "int"}, {"name": "value", "type": "int"}],
    description: "Set bridge baud (9600-115200)",
    serialOnly: false,
    hasParam: true,
  },
  {
    name: "set bridge.channel",
    category: "set",
    params: [{"name": "value", "type": "int"}, {"name": "value", "type": "string"}],
    description: "Set bridge channel (1-14)",
    serialOnly: false,
    hasParam: true,
  },
  {
    name: "set bridge.delay",
    category: "set",
    params: [{"name": "value", "type": "int"}],
    description: "Set bridge delay (0-10000 ms)",
    serialOnly: false,
    hasParam: true,
  },
  {
    name: "set bridge.enabled",
    category: "set",
    params: [{"name": "value", "type": "int"}],
    description: "Enable/disable bridge",
    serialOnly: false,
    hasParam: true,
  },
  {
    name: "set bridge.secret",
    category: "set",
    params: [{"name": "value", "type": "string"}, {"name": "value", "type": "float"}],
    description: "Set bridge encryption secret",
    serialOnly: false,
    hasParam: true,
  },
  {
    name: "set bridge.source",
    category: "set",
    params: [{"name": "value", "type": "int"}],
    description: "Set bridge source (rx/tx)",
    serialOnly: false,
    hasParam: true,
  },
  {
    name: "set direct.txdelay",
    category: "set",
    params: [{"name": "value", "type": "float"}, {"name": "value", "type": "int"}],
    description: "Set direct TX delay factor",
    serialOnly: false,
    hasParam: true,
  },
  {
    name: "set flood.advert.interval",
    category: "set",
    params: [{"name": "value", "type": "int"}, {"name": "value", "type": "int"}],
    description: "Set flood advert interval (3-48 hours, 0=off)",
    serialOnly: false,
    hasParam: true,
  },
  {
    name: "set flood.max",
    category: "set",
    params: [{"name": "value", "type": "int"}, {"name": "value", "type": "float"}],
    description: "Set max flood hops (0-64)",
    serialOnly: false,
    hasParam: true,
  },
  {
    name: "set freq",
    category: "set",
    params: [{"name": "value", "type": "float"}, {"name": "value", "type": "int"}],
    description: "Set frequency MHz (serial only, reboot required)",
    serialOnly: true,
    hasParam: true,
  },
  {
    name: "set guest.password",
    category: "set",
    params: [{"name": "value", "type": "string"}],
    description: "Set guest password",
    serialOnly: false,
    hasParam: true,
  },
  {
    name: "set int.thresh",
    category: "set",
    params: [{"name": "value", "type": "int"}, {"name": "value", "type": "int"}, {"name": "value", "type": "int"}],
    description: "Set interference threshold",
    serialOnly: false,
    hasParam: true,
  },
  {
    name: "set lat",
    category: "set",
    params: [{"name": "value", "type": "float"}, {"name": "value", "type": "float"}, {"name": "value", "type": "float"}],
    description: "Set latitude",
    serialOnly: false,
    hasParam: true,
  },
  {
    name: "set lon",
    category: "set",
    params: [{"name": "value", "type": "float"}, {"name": "value", "type": "float"}, {"name": "value", "type": "float"}],
    description: "Set longitude",
    serialOnly: false,
    hasParam: true,
  },
  {
    name: "set multi.acks",
    category: "set",
    params: [{"name": "value", "type": "int"}, {"name": "value", "type": "int"}],
    description: "Set multi-ack (0/1)",
    serialOnly: false,
    hasParam: true,
  },
  {
    name: "set name",
    category: "set",
    params: [{"name": "value", "type": "string"}, {"name": "value", "type": "int"}],
    description: "Set node name",
    serialOnly: false,
    hasParam: true,
  },
  {
    name: "set prv.key",
    category: "set",
    params: [{"name": "value", "type": "string"}],
    description: "Set private key (serial only)",
    serialOnly: true,
    hasParam: true,
  },
  {
    name: "set radio",
    category: "set",
    params: [{"name": "value", "type": "int"}, {"name": "value", "type": "int"}],
    description: "Set radio params (freq bw sf cr)",
    serialOnly: false,
    hasParam: true,
  },
  {
    name: "set repeat",
    category: "set",
    params: [{"name": "value", "type": "int"}, {"name": "value", "type": "int"}],
    description: "Set repeat/forward (on/off)",
    serialOnly: false,
    hasParam: true,
  },
  {
    name: "set rxdelay",
    category: "set",
    params: [{"name": "value", "type": "float"}, {"name": "value", "type": "float"}],
    description: "Set RX delay base",
    serialOnly: false,
    hasParam: true,
  },
  {
    name: "set tx",
    category: "set",
    params: [{"name": "value", "type": "int"}, {"name": "value", "type": "float"}],
    description: "Set TX power (dBm)",
    serialOnly: false,
    hasParam: true,
  },
  {
    name: "set txdelay",
    category: "set",
    params: [{"name": "value", "type": "float"}, {"name": "value", "type": "int"}],
    description: "Set TX delay factor",
    serialOnly: false,
    hasParam: true,
  },
  {
    name: "stats-core",
    category: "stats",
    params: [],
    description: "Show core statistics (serial only)",
    serialOnly: true,
    hasParam: false,
  },
  {
    name: "stats-packets",
    category: "stats",
    params: [],
    description: "Show packet statistics (serial only)",
    serialOnly: true,
    hasParam: false,
  },
  {
    name: "stats-radio",
    category: "stats",
    params: [],
    description: "Show radio statistics (serial only)",
    serialOnly: true,
    hasParam: false,
  },
  {
    name: "advert",
    category: "system",
    params: [],
    description: "Send self advertisement",
    serialOnly: false,
    hasParam: false,
  },
  {
    name: "board",
    category: "system",
    params: [],
    description: "Show board/manufacturer name",
    serialOnly: false,
    hasParam: false,
  },
  {
    name: "clear stats",
    category: "system",
    params: [],
    description: "Reset statistics counters",
    serialOnly: false,
    hasParam: true,
  },
  {
    name: "clock",
    category: "system",
    params: [{"name": "value", "type": "int"}],
    description: "Display current time",
    serialOnly: false,
    hasParam: true,
  },
  {
    name: "clock sync",
    category: "system",
    params: [],
    description: "Sync clock from sender timestamp",
    serialOnly: false,
    hasParam: true,
  },
  {
    name: "password",
    category: "system",
    params: [{"name": "value", "type": "string"}],
    description: "Change admin password",
    serialOnly: false,
    hasParam: true,
  },
  {
    name: "reboot",
    category: "system",
    params: [],
    description: "Reboot the device",
    serialOnly: false,
    hasParam: false,
  },
  {
    name: "start ota",
    category: "system",
    params: [{"name": "value", "type": "int"}],
    description: "Start OTA firmware update",
    serialOnly: false,
    hasParam: true,
  },
  {
    name: "time",
    category: "system",
    params: [{"name": "value", "type": "int"}],
    description: "Set time to epoch seconds",
    serialOnly: false,
    hasParam: true,
  },
  {
    name: "ver",
    category: "system",
    params: [],
    description: "Show firmware version and build date",
    serialOnly: false,
    hasParam: false,
  },
];

export const MESHCORE_CATEGORIES = ["get", "gps", "logging", "neighbor", "other", "radio", "sensor", "set", "stats", "system"];
